require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/compte_clients", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CompteClient. As you add validations to CompteClient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CompteClient.create! valid_attributes
      get compte_clients_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      compte_client = CompteClient.create! valid_attributes
      get compte_client_url(compte_client)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_compte_client_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      compte_client = CompteClient.create! valid_attributes
      get edit_compte_client_url(compte_client)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CompteClient" do
        expect {
          post compte_clients_url, params: { compte_client: valid_attributes }
        }.to change(CompteClient, :count).by(1)
      end

      it "redirects to the created compte_client" do
        post compte_clients_url, params: { compte_client: valid_attributes }
        expect(response).to redirect_to(compte_client_url(CompteClient.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CompteClient" do
        expect {
          post compte_clients_url, params: { compte_client: invalid_attributes }
        }.to change(CompteClient, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post compte_clients_url, params: { compte_client: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested compte_client" do
        compte_client = CompteClient.create! valid_attributes
        patch compte_client_url(compte_client), params: { compte_client: new_attributes }
        compte_client.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the compte_client" do
        compte_client = CompteClient.create! valid_attributes
        patch compte_client_url(compte_client), params: { compte_client: new_attributes }
        compte_client.reload
        expect(response).to redirect_to(compte_client_url(compte_client))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        compte_client = CompteClient.create! valid_attributes
        patch compte_client_url(compte_client), params: { compte_client: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested compte_client" do
      compte_client = CompteClient.create! valid_attributes
      expect {
        delete compte_client_url(compte_client)
      }.to change(CompteClient, :count).by(-1)
    end

    it "redirects to the compte_clients list" do
      compte_client = CompteClient.create! valid_attributes
      delete compte_client_url(compte_client)
      expect(response).to redirect_to(compte_clients_url)
    end
  end
end
