require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/credits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Credit. As you add validations to Credit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Credit.create! valid_attributes
      get credits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      credit = Credit.create! valid_attributes
      get credit_url(credit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_credit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      credit = Credit.create! valid_attributes
      get edit_credit_url(credit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Credit" do
        expect {
          post credits_url, params: { credit: valid_attributes }
        }.to change(Credit, :count).by(1)
      end

      it "redirects to the created credit" do
        post credits_url, params: { credit: valid_attributes }
        expect(response).to redirect_to(credit_url(Credit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Credit" do
        expect {
          post credits_url, params: { credit: invalid_attributes }
        }.to change(Credit, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post credits_url, params: { credit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested credit" do
        credit = Credit.create! valid_attributes
        patch credit_url(credit), params: { credit: new_attributes }
        credit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the credit" do
        credit = Credit.create! valid_attributes
        patch credit_url(credit), params: { credit: new_attributes }
        credit.reload
        expect(response).to redirect_to(credit_url(credit))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        credit = Credit.create! valid_attributes
        patch credit_url(credit), params: { credit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested credit" do
      credit = Credit.create! valid_attributes
      expect {
        delete credit_url(credit)
      }.to change(Credit, :count).by(-1)
    end

    it "redirects to the credits list" do
      credit = Credit.create! valid_attributes
      delete credit_url(credit)
      expect(response).to redirect_to(credits_url)
    end
  end
end
